// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MessageBustsMZ","status":false,"description":"(v.1.2) Displays a bust image instead of selected face image","parameters":{"bPriority":"0","bPosition":"0","bX":"0","bY":"0","xOffset":"390","fileAppend":"","mStyleBusts":"false"}},
{"name":"IgnisItemGoldPopup","status":false,"description":"Item and Gold Popup v.1.0.0","parameters":{"switchPopUp":"true","windowWidth":"60","windowHeight":"60","dynamic":"true","outlineSize":"1","fontSize":"20","fontName":"","fontColorGold":"FFFFFF","outlineColorGold":"FFFFFF","fontColorItem":"FFFFFF","outlineColorItem":"FFFFFF","fontColorWeapon":"FFFFFF","outlineColorWeapon":"FFFFFF","fontColorEquip":"FFFFFF","outlineColorEquip":"FFFFFF"}},
{"name":"IgnisTextDatabase","status":true,"description":"Text Database v.1.0.1","parameters":{"defaultFolder":"text","textFiles":"[\"de\"]","defaultFile":"de"}}
];
